FROM nginx:alpine

COPY frontend/default.conf /etc/nginx/conf.d/default.conf
COPY frontend/index.html /usr/share/nginx/html/index.html
COPY frontend/style.css /usr/share/nginx/html/style.css

EXPOSE 8080

# vim:sw=2:ts=2:et:set filetype=dockerfile :
